### ISSUE TITLE
Are there any plans to support retrieving all translations for an entry

### ISSUE THREAD

**Issue by blazingarrow** [nascentdigital/contentfully#14]
Thank you for _contentfully_, it helps me a lot.

Are there any plans to support [retrieving all translations for an entry](https://www.contentful.com/developers/docs/tutorials/general/setting-locales/#retrieving-all-translations-for-an-entry) with the wildcard parameter? Currently I can fetch only one locale at a time. For some edge cases (fetch translated slug) it would be really helpful to get the items with all locales.

The response would look like this:
```json
{
    "items": {
        "de-CH": {
         
       },
        "fr-CH": {

       },
    }
}
```

**Comment by bernietrinh** [comment]
Hi @blazingarrow thanks for the feedback! We'll look into adding this support soon and let you know.

**Comment by bernietrinh** [comment]
@blazingarrow sorry for the delay - we've now added support for retrieving all locales. Please refer to the README for v1.4.0 and let us know any feedback

**Comment by blazingarrow** [comment]
@bernietrinh 🙇
