### ISSUE TITLE
Error when entry reference is not published

### ISSUE THREAD

**Issue by kretzm** [nascentdigital/contentfully#5]
### Issue
When a published entry has a reference that is unpublished, we are getting an error thrown back to us.
`'TypeError: Cannot read property \'_deferred\' of undefined',
'at Contentfully._dereferenceLink (.../contentfully/dist/Contentfully.js:94:18)'`

This is using the Delivery API, we haven't tested if the issue is the same in the preview API

Offending function:
https://github.com/nascentdigital/contentfully/blob/e7f2cfd11bbe5a393b38348ac4ed0a131dc900c8/src/Contentfully.ts#L110

### Expected
Ideally, if a reference is unpublished, we shouldn't get an error. Only return references that are published and ignore unpublished references. As a content editor, if I leave something in draft mode, I wouldn't want to see it on my published page.

**Comment by bernietrinh** [comment]
@kretzm this is fixed [here](https://github.com/nascentdigital/contentfully/commit/b0ffd08579a8d8a27060c8d291bcb0c1bcb16f02).
